### ISSUE TITLE
Doesn't follow scale

### ISSUE THREAD

**Issue by ZachAR3** [ZachAR3/Destructibles-CSharp#4]
Shard scenes don't follow the parents scale even when dynamically generated

**Comment by ZachAR3** [comment]
@valkyrienyanko Any clues on this? Not getting any help on the forums haha. The shards themselves follow the scale but when I try and scale the container or parent it doesn't work, and scaling just the shards doesn't move their position so they are glitched in one another.

**Comment by valkyrienyanko** [comment]
I only looked at the C# to quickly touch up some things here and there. But I never tried testing out the project itself. I will try to understand this project more since you mentioned me. But for now I sleep as it is 3 am.

**Comment by ZachAR3** [comment]
> e

Ah no problem if no problem, you just seemed quite knowledge in this so thought I would try haha.

**Comment by valkyrienyanko** [comment]
https://user-images.githubusercontent.com/6277739/235366345-2a621a8d-13e0-4115-9200-36f048f54eb6.mp4

Works for me?

Unless you are talking about the first cube that spawns in?

**Comment by ZachAR3** [comment]
Yeah, the shards follow the scale but they spawn inside each other because their positions aren't scaled. This means they bug out as seen in your video. If possible I would like for their positions to all move accordingly so without explosive power it just falls flat like the 1x scale cube.

**Comment by ZachAR3** [comment]
Any ideas?
