### ISSUE TITLE
Should the destroy method be private?

### ISSUE THREAD

**Issue by RichP** [ZachAR3/Destructibles-CSharp#9]
I followed the Readme but, had to make this public in order to shatter my mesh.

**Comment by ZachAR3** [comment]
I don't experience this, for me just calling .destroy on the object works fine. How are you trying to call it? You should do it by calling it from the object destroying it, e.g cube.destroy()

**Comment by CryReaper** [comment]
I also had to make the method public in order to call it from another object in C#.

![image](https://github.com/ZachAR3/Destructibles-CSharp/assets/14111670/a4f532f9-04c7-49eb-8234-af0c0631c95b)

**Comment by ZachAR3** [comment]
> I also had to make the method public in order to call it from another object in C#.
> 
> ![image](https://private-user-images.githubusercontent.com/14111670/289310864-a4f532f9-04c7-49eb-8234-af0c0631c95b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxODg4MDEsIm5iZiI6MTcwMjE4ODUwMSwicGF0aCI6Ii8xNDExMTY3MC8yODkzMTA4NjQtYTRmNTMyZjktMDRjNy00OWViLTgyMzQtYWYwYzA2MzFjOTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDA2MDgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MGI0ZTI2NmY2MDZiOGVlYWRlMTI1YmYyZThhOTBhOTc5OTRmMzEzNmI3YTRiNjc5MzZhOGE0MWFkNzUyODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WFMYrhRDMzjxUHGoRLD6B0ILkMwd3h0euSJDqx5o0BQ)

Can you show me how you're calling it? In my demo it calls just fine as a private so I wanna see what ways it doesn't
The way demo calls:
```
extends Node3D

@onready var destruction = $DestructibleCube/Destructible
@onready var destroy_button: Button = $DestroyButton

var destructible_cube_scene := preload("res://Demo/destructible_cube.tscn")

func _on_destroy_button_pressed() -> void:
	destruction.Destroy(10, Vector3.ZERO)
	destroy_button.disabled = true
	await get_tree().create_timer(1).timeout
	var new := destructible_cube_scene.instantiate()
	add_child(new)
	destruction = new.get_node("Destructible")
	destroy_button.disabled = false
```

**Comment by CryReaper** [comment]
I'm not definitely sure, but I think GDScript can call private C# methods.  If you're using C# to call the method it won't be accessible unless you're calling from within the methods class.  Changing it to public allows it to be called from other classes.

If I set the function back to private and try calling from a different script with a reference to the Destructible it gives this error:
![image](https://github.com/ZachAR3/Destructibles-CSharp/assets/14111670/f2a52a5e-167d-4f66-a352-65d3ad337882)

**Comment by ZachAR3** [comment]
Gotcha, I hadn't tried it through C# so just wanted to double check before editing it. Will send a commit with that fixed now and update the asset store version too. Thanks!
